on:
  pull_request:

jobs:
  build:
    name: Build bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Build bot
        run: "python3 src"
        env:
          PR_TESTING: 1